package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.City;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int updateByPrimaryKey(City record);
}