package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.CoronaCase;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CoronaCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CORONA_CASE
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CORONA_CASE
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int insert(CoronaCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CORONA_CASE
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    CoronaCase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CORONA_CASE
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    List<CoronaCase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CORONA_CASE
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int updateByPrimaryKey(CoronaCase record);
}