package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Location;
import org.mybatis.cdi.Mapper;

@Mapper
public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    Location selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    List<Location> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int updateByPrimaryKey(Location record);
}