package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.PersonLocation;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PersonLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON_LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON_LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int insert(PersonLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON_LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    PersonLocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON_LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    List<PersonLocation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON_LOCATION
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    int updateByPrimaryKey(PersonLocation record);
}