package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.COUNTRY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.NAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.ID
     *
     * @return the value of PUBLIC.CITY.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.ID
     *
     * @param id the value for PUBLIC.CITY.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.COUNTRY
     *
     * @return the value of PUBLIC.CITY.COUNTRY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.COUNTRY
     *
     * @param country the value for PUBLIC.CITY.COUNTRY
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.NAME
     *
     * @return the value of PUBLIC.CITY.NAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.NAME
     *
     * @param name the value for PUBLIC.CITY.NAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    // Added manually
    @Getter @Setter
    private List<Location> locations;
}