package lt.vu.mybatis.model;

import java.util.Date;

public class CoronaCase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CORONA_CASE.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CORONA_CASE.PERSON_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CORONA_CASE.DATE_DISCOVERED
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Date dateDiscovered;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CORONA_CASE.ID
     *
     * @return the value of PUBLIC.CORONA_CASE.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CORONA_CASE.ID
     *
     * @param id the value for PUBLIC.CORONA_CASE.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CORONA_CASE.PERSON_ID
     *
     * @return the value of PUBLIC.CORONA_CASE.PERSON_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CORONA_CASE.PERSON_ID
     *
     * @param personId the value for PUBLIC.CORONA_CASE.PERSON_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CORONA_CASE.DATE_DISCOVERED
     *
     * @return the value of PUBLIC.CORONA_CASE.DATE_DISCOVERED
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Date getDateDiscovered() {
        return dateDiscovered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CORONA_CASE.DATE_DISCOVERED
     *
     * @param dateDiscovered the value for PUBLIC.CORONA_CASE.DATE_DISCOVERED
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setDateDiscovered(Date dateDiscovered) {
        this.dateDiscovered = dateDiscovered;
    }
}