package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

public class PersonLocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON_LOCATION.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON_LOCATION.DATE_VISITED
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Date dateVisited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON_LOCATION.LOCATION_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON_LOCATION.PERSON_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Integer personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON_LOCATION.ID
     *
     * @return the value of PUBLIC.PERSON_LOCATION.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON_LOCATION.ID
     *
     * @param id the value for PUBLIC.PERSON_LOCATION.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON_LOCATION.DATE_VISITED
     *
     * @return the value of PUBLIC.PERSON_LOCATION.DATE_VISITED
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Date getDateVisited() {
        return dateVisited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON_LOCATION.DATE_VISITED
     *
     * @param dateVisited the value for PUBLIC.PERSON_LOCATION.DATE_VISITED
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setDateVisited(Date dateVisited) {
        this.dateVisited = dateVisited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON_LOCATION.LOCATION_ID
     *
     * @return the value of PUBLIC.PERSON_LOCATION.LOCATION_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON_LOCATION.LOCATION_ID
     *
     * @param locationId the value for PUBLIC.PERSON_LOCATION.LOCATION_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON_LOCATION.PERSON_ID
     *
     * @return the value of PUBLIC.PERSON_LOCATION.PERSON_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON_LOCATION.PERSON_ID
     *
     * @param personId the value for PUBLIC.PERSON_LOCATION.PERSON_ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    //Added Manually
    @Getter @Setter
    private Location location;
}