package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.EMAIL
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.NAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.SURNAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.ID
     *
     * @return the value of PUBLIC.PERSON.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.ID
     *
     * @param id the value for PUBLIC.PERSON.ID
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.EMAIL
     *
     * @return the value of PUBLIC.PERSON.EMAIL
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.EMAIL
     *
     * @param email the value for PUBLIC.PERSON.EMAIL
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.NAME
     *
     * @return the value of PUBLIC.PERSON.NAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.NAME
     *
     * @param name the value for PUBLIC.PERSON.NAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.SURNAME
     *
     * @return the value of PUBLIC.PERSON.SURNAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.SURNAME
     *
     * @param surname the value for PUBLIC.PERSON.SURNAME
     *
     * @mbg.generated Tue Apr 14 11:10:38 EEST 2020
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    //Added manually
    @Getter @Setter
    private CoronaCase corona;

    @Getter @Setter
    private List<PersonLocation> locations;

    public boolean hasCorona() {
        return this.corona != null;
    }
}